<TestCanvas@BoxLayout>:
    canvas:
        # This is a comment
        Color:
            rgb: 1, 0, 0
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        text: "This is a test canvas."
    Label:
        text: "This is a test canvas with a comment."
    BoxLayout:
        minimum_height: 1
        minimum_size: 1
        minimum_width: 1
        orientation: 'horizontal'
        padding: 1
        spacing: 2
    Button:
        background_color: "red"
        background_disabled_down: ""
        background_disabled_normal: ""
        background_down: None
        background_normal: None
        border: [2,2]
    


# <MyWidget>:
#     Label:
#         text: "Hello, World!"